yad --width=200 --title="" --text="Connexion :" \
--undecorated \
--form \
--text "Pour accèder à cette borne, vous devez\nconsulter la charte ci-contre et saisir\nles informations suivantes :" \
--field="Prénom" \
--field="Nom" \
--dialog-sep \
--field="J'accepte la charte d'utilisation du réseau":CHK \
--button="Annuler:1" \
--dialog-sep \
--button="Se connecter:0"